### ISSUE TITLE
Remove Rcplex and instead work with cplexAPI 

### ISSUE THREAD

**Issue by adamsardar** [adamsardar/stoneTrees#10]
@JulieBorgel tells me that Rcplex does not build with the latest CPLEX library. I no longer have access to CPLEX and frankly their decision to recluse themselves from [community benchmarks](http://plato.asu.edu/bench.html) is weak sauce, so I am reluctant to provide much support for their tools.

cplexAPI should suffice for our needs. Testing is tricky of course ...

**Comment by jonnywray** [comment]
I've tested functionally via creating a Docker image with only cplexAPI installed and it seems to work OK. I can do more extensive testing as you wish.

Rcplex was last updated years back and cplexAPI was this year.

**Comment by adamsardar** [comment]
I also found a bug in Rcplex with a very large number of constraints.

Let me look at the cplex community edition and see if we can use it for some testing.
